library(MASS)
A = data.frame(Cars93)
str(A)
hist(A$Manufacturer)
str(A)
hist(A$Horsepower)
A1 = A[1:20,]
A1
hist(A1$Horsepower)
A1
A1$Horsepower
table(A1$Horsepower)
table(A1$RPM)
hist(A1$Horsepower,col = 3)
hist(A1$Horsepower,col = 3:10)
table(A1$Horsepower,col = 1:5)
hist(A1$RPM,col = 1:5)
hist(A1$RPM,col = 1)
hist(A1$Horsepower,col = c(2,2,2,2,9))
hist(A1$RPM,col = c(2,2,2,2,3))
par(mfrow=c(2,2))
hist(A1$RPM,col = c(2,2,2,2,3))
hist(A1$RPM,col = c(2,3,4,2,6))
hist(A1$RPM,col = c(2,2,2,2,3))
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$Horsepower,col = 2)
hist(A1$RPM,col = 3)
hist(A1$RPM,col = 4)
par(mfrow=c(3,2))
hist(A1$RPM,col = 4)
hist(A1$RPM,col = 42)
hist(A1$RPM,col = 3)
hist(A1$RPM,col = 4)
hist(A1$RPM,col = 5)
hist(A1$RPM,col = 6)
hist(A1$RPM,col = 2,main = "Histogram of RPM's with repeat frequency")
par(mfrow=c(1,1))
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency")
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines")
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines",ylab = "Repetation frequency")
hist(A1$RPM,col = "blue",main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines",ylab = "Repetation frequency")
?hist

hist(A1$Horsepower,col = "blue",main = "Histogram of Horsepower's with repeat frequency",xlab = "Horsepower of engines",ylab = "Repetation frequency",labels = TRUE,breaks = seq(50,100,10))

